name: Build

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

defaults:
  run:
    working-directory: ./client/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm packages
        run: npm i

      - name: Build React
        run: npm run build
